services:
  spark:
    image: docker.io/bitnami/spark:3
    networks:
      - crypto-network
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    ports:
      - '8000:8000'
  spark-worker:
    image: docker.io/bitnami/spark:3
    networks:
      - crypto-network
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
      - SPARK_WORKER_MEMORY=3G
      - SPARK_WORKER_CORES=6
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no

  redis:
    image: redis:latest
    networks:
      - crypto-network
    ports:
      - '6379:6379'

  fastapi-app:
    build:
      context: .
      dockerfile: Dockerfile.restapi
    networks:
      - crypto-network
    ports:
      - '8080:8080'
    depends_on:
      - redis


networks:
  crypto-network:
    name: crypto-network
    external: true
